# Site's name:
name: 'VanCal'

# Site's tagline:
tagline: "Vancouver's Tech Calendar"

# Site's URL with trailing slash:
url: 'http://vancal.pixelcrafters.ca'

# Default timezone, run "rake -D time" for information on how to display known timezones:
timezone: 'Pacific Time (US & Canada)'

# Google map to display on /venues page:
venues_google_map_options:
  # Zoom magnification level:
  zoom: 12
  # Center of the map, in latitude and longitude:
  center: [37.0625, -95.677068]

# Array of tag names to exclude from tag cloud:
tagcloud_exclusions:
  - free
  - paid
